<?php
/**
 * Plugin bootstrap and admin controller.
 *
 * @package IndexLaneSafeWebPQueue
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Main plugin controller.
 */
class ILSWQ_Plugin {
	/**
	 * Singleton instance.
	 *
	 * @var ILSWQ_Plugin|null
	 */
	private static $instance = null;

	/**
	 * Admin page hook suffix.
	 *
	 * @var string
	 */
	private $hook_suffix = '';

	/**
	 * Scanner instance.
	 *
	 * @var ILSWQ_Scanner
	 */
	private $scanner;

	/**
	 * Converter instance.
	 *
	 * @var ILSWQ_Converter
	 */
	private $converter;

	/**
	 * Return singleton instance.
	 *
	 * @return ILSWQ_Plugin
	 */
	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	/**
	 * Constructor.
	 */
	private function __construct() {
		$this->scanner   = new ILSWQ_Scanner();
		$this->converter = new ILSWQ_Converter( $this->scanner );

		add_action( 'init', array( $this, 'load_textdomain' ) );
		add_action( 'admin_menu', array( $this, 'add_admin_page' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_assets' ) );

		add_action( 'wp_ajax_ilswq_save_settings', array( $this, 'ajax_save_settings' ) );
		add_action( 'wp_ajax_ilswq_scan', array( $this, 'ajax_scan' ) );
		add_action( 'wp_ajax_ilswq_convert', array( $this, 'ajax_convert' ) );
		add_action( 'wp_ajax_ilswq_cleanup', array( $this, 'ajax_cleanup' ) );
		add_action( 'wp_ajax_ilswq_validate_webp', array( $this, 'ajax_validate_webp' ) );

		add_filter( 'wp_get_attachment_image_src', array( 'ILSWQ_Serving', 'filter_attachment_image_src' ), 10, 4 );
		add_filter( 'wp_calculate_image_srcset', array( 'ILSWQ_Serving', 'filter_image_srcset' ), 10, 5 );
		add_filter( 'wp_generate_attachment_metadata', array( $this, 'maybe_convert_upload_metadata' ), 20, 2 );
	}

	/**
	 * Load translations.
	 *
	 * @return void
	 */
	public function load_textdomain() {
		load_plugin_textdomain(
			'indexlane-safe-webp-queue',
			false,
			dirname( plugin_basename( ILSWQ_FILE ) ) . '/languages'
		);
	}

	/**
	 * Add Tools page.
	 *
	 * @return void
	 */
	public function add_admin_page() {
		$this->hook_suffix = add_management_page(
			__( 'Safe WebP Queue', 'indexlane-safe-webp-queue' ),
			__( 'Safe WebP Queue', 'indexlane-safe-webp-queue' ),
			'manage_options',
			'indexlane-safe-webp-queue',
			array( $this, 'render_admin_page' )
		);
	}

	/**
	 * Enqueue admin assets.
	 *
	 * @param string $hook Current admin hook.
	 * @return void
	 */
	public function enqueue_admin_assets( $hook ) {
		if ( $hook !== $this->hook_suffix ) {
			return;
		}

		wp_enqueue_style(
			'ilswq-admin',
			ILSWQ_URL . 'assets/admin.css',
			array(),
			ILSWQ_VERSION
		);

		wp_enqueue_script(
			'ilswq-admin',
			ILSWQ_URL . 'assets/admin.js',
			array( 'jquery' ),
			ILSWQ_VERSION,
			true
		);

		wp_localize_script(
			'ilswq-admin',
			'ILSWQ_Admin',
			array(
				'ajaxUrl'  => admin_url( 'admin-ajax.php' ),
				'nonce'    => wp_create_nonce( 'ilswq_admin' ),
				'settings' => ILSWQ_Settings::get(),
				'strings'  => array(
					'scanning'       => __( 'Scanning Media Library...', 'indexlane-safe-webp-queue' ),
					'scanComplete'   => __( 'Scan complete.', 'indexlane-safe-webp-queue' ),
					'converting'     => __( 'Converting selected images...', 'indexlane-safe-webp-queue' ),
					'convertComplete'=> __( 'Conversion queue complete.', 'indexlane-safe-webp-queue' ),
					'noRows'         => __( 'Run a scan to build a report.', 'indexlane-safe-webp-queue' ),
					'noEligible'     => __( 'No eligible rows are selected.', 'indexlane-safe-webp-queue' ),
					'settingsSaved'  => __( 'Settings saved.', 'indexlane-safe-webp-queue' ),
					'cleanupConfirm' => __( 'Delete WebP files generated by this plugin and clear their metadata?', 'indexlane-safe-webp-queue' ),
					'cleanupDone'    => __( 'Generated WebP cleanup complete.', 'indexlane-safe-webp-queue' ),
					'cleanupRefresh' => __( 'Run a new scan to refresh the report.', 'indexlane-safe-webp-queue' ),
					'cleanupRunning' => __( 'Cleaning generated WebP files...', 'indexlane-safe-webp-queue' ),
					'deleted'        => __( 'Deleted', 'indexlane-safe-webp-queue' ),
					'failed'         => __( 'Failed', 'indexlane-safe-webp-queue' ),
					'paused'         => __( 'Queue paused.', 'indexlane-safe-webp-queue' ),
					'stopped'        => __( 'Queue stopped.', 'indexlane-safe-webp-queue' ),
					'validationPassed' => __( 'Generated WebP file is valid.', 'indexlane-safe-webp-queue' ),
				),
			)
		);
	}

	/**
	 * Render admin page.
	 *
	 * @return void
	 */
	public function render_admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_die( esc_html__( 'You do not have permission to access this page.', 'indexlane-safe-webp-queue' ) );
		}

		$settings = ILSWQ_Settings::get();
		$checks   = ILSWQ_Capabilities::get_checks();
		?>
		<div class="wrap ilswq-wrap">
			<h1><?php esc_html_e( 'Safe WebP Queue', 'indexlane-safe-webp-queue' ); ?></h1>
			<p class="ilswq-lede">
				<?php esc_html_e( 'Convert JPEG and PNG media attachments and their generated image sizes to sibling WebP files in small local batches. Originals are preserved and post content is not rewritten.', 'indexlane-safe-webp-queue' ); ?>
			</p>
			<p class="ilswq-lede">
				<?php esc_html_e( 'Frontend WebP serving is optional and only swaps normal WordPress image output where this plugin has generated a matching WebP file.', 'indexlane-safe-webp-queue' ); ?>
			</p>

			<div class="ilswq-layout">
				<section class="ilswq-panel">
					<h2><?php esc_html_e( 'Server Checks', 'indexlane-safe-webp-queue' ); ?></h2>
					<table class="widefat striped ilswq-checks">
						<tbody>
							<?php foreach ( $checks as $check ) : ?>
								<tr class="ilswq-check-row is-<?php echo esc_attr( $check['status'] ); ?>">
									<th scope="row"><?php echo esc_html( $check['label'] ); ?></th>
									<td><strong><?php echo esc_html( $check['value'] ); ?></strong></td>
									<td><?php echo esc_html( $check['description'] ); ?></td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
				</section>

				<section class="ilswq-panel">
					<h2><?php esc_html_e( 'Queue Settings', 'indexlane-safe-webp-queue' ); ?></h2>
					<form id="ilswq-settings-form" class="ilswq-settings-form">
						<label>
							<span><?php esc_html_e( 'Batch size', 'indexlane-safe-webp-queue' ); ?></span>
							<input type="number" min="1" max="10" name="batch_size" value="<?php echo esc_attr( $settings['batch_size'] ); ?>">
						</label>
						<label>
							<span><?php esc_html_e( 'Max pixels', 'indexlane-safe-webp-queue' ); ?></span>
							<input type="number" min="1000000" max="40000000" step="1000000" name="max_pixels" value="<?php echo esc_attr( $settings['max_pixels'] ); ?>">
						</label>
						<label>
							<span><?php esc_html_e( 'JPEG quality', 'indexlane-safe-webp-queue' ); ?></span>
							<input type="number" min="1" max="100" name="jpeg_quality" value="<?php echo esc_attr( $settings['jpeg_quality'] ); ?>">
						</label>
						<label>
							<span><?php esc_html_e( 'PNG quality', 'indexlane-safe-webp-queue' ); ?></span>
							<input type="number" min="1" max="100" name="png_quality" value="<?php echo esc_attr( $settings['png_quality'] ); ?>">
						</label>
						<label class="ilswq-checkbox">
							<input type="checkbox" name="skip_larger" value="1" <?php checked( $settings['skip_larger'], 1 ); ?>>
							<span><?php esc_html_e( 'Skip when WebP is larger', 'indexlane-safe-webp-queue' ); ?></span>
						</label>
						<label class="ilswq-checkbox">
							<input type="checkbox" name="serve_webp" value="1" <?php checked( $settings['serve_webp'], 1 ); ?>>
							<span><?php esc_html_e( 'Use generated WebP in WordPress image output', 'indexlane-safe-webp-queue' ); ?></span>
						</label>
						<label class="ilswq-checkbox">
							<input type="checkbox" name="auto_uploads" value="1" <?php checked( $settings['auto_uploads'], 1 ); ?>>
							<span><?php esc_html_e( 'Generate WebP for new uploads', 'indexlane-safe-webp-queue' ); ?></span>
						</label>
						<button type="submit" class="button"><?php esc_html_e( 'Save Settings', 'indexlane-safe-webp-queue' ); ?></button>
					</form>
				</section>
			</div>

			<section class="ilswq-panel ilswq-report-panel">
				<div class="ilswq-toolbar">
					<div class="ilswq-actions">
						<button type="button" class="button button-primary" id="ilswq-scan"><?php esc_html_e( 'Scan Media Library', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-resume" disabled><?php esc_html_e( 'Resume', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-pause" disabled><?php esc_html_e( 'Pause', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-stop" disabled><?php esc_html_e( 'Stop', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-convert" disabled><?php esc_html_e( 'Convert Selected', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-validate-webp" disabled><?php esc_html_e( 'Validate WebP', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button" id="ilswq-export" disabled><?php esc_html_e( 'Export CSV', 'indexlane-safe-webp-queue' ); ?></button>
						<button type="button" class="button ilswq-danger" id="ilswq-cleanup"><?php esc_html_e( 'Delete Generated WebPs', 'indexlane-safe-webp-queue' ); ?></button>
					</div>
					<div class="ilswq-counters" aria-live="polite">
						<span><strong id="ilswq-count-total">0</strong> <?php esc_html_e( 'total', 'indexlane-safe-webp-queue' ); ?></span>
						<span><strong id="ilswq-count-eligible">0</strong> <?php esc_html_e( 'eligible', 'indexlane-safe-webp-queue' ); ?></span>
						<span><strong id="ilswq-count-converted">0</strong> <?php esc_html_e( 'converted', 'indexlane-safe-webp-queue' ); ?></span>
						<span><strong id="ilswq-count-skipped">0</strong> <?php esc_html_e( 'skipped', 'indexlane-safe-webp-queue' ); ?></span>
						<span><strong id="ilswq-count-failed">0</strong> <?php esc_html_e( 'failed', 'indexlane-safe-webp-queue' ); ?></span>
						<span><strong id="ilswq-count-needs-review">0</strong> <?php esc_html_e( 'needs review', 'indexlane-safe-webp-queue' ); ?></span>
					</div>
				</div>

				<div id="ilswq-progress" class="ilswq-progress" hidden>
					<div class="ilswq-progress-bar"><span></span></div>
					<p></p>
				</div>

				<div id="ilswq-notice" class="ilswq-notice" hidden></div>

				<div class="ilswq-filters" aria-label="<?php esc_attr_e( 'Filter scan results', 'indexlane-safe-webp-queue' ); ?>">
					<button type="button" class="button is-active" data-ilswq-filter="all"><?php esc_html_e( 'All', 'indexlane-safe-webp-queue' ); ?></button>
					<button type="button" class="button" data-ilswq-filter="eligible"><?php esc_html_e( 'Eligible', 'indexlane-safe-webp-queue' ); ?></button>
					<button type="button" class="button" data-ilswq-filter="converted"><?php esc_html_e( 'Converted', 'indexlane-safe-webp-queue' ); ?></button>
					<button type="button" class="button" data-ilswq-filter="skipped"><?php esc_html_e( 'Skipped', 'indexlane-safe-webp-queue' ); ?></button>
					<button type="button" class="button" data-ilswq-filter="failed"><?php esc_html_e( 'Failed', 'indexlane-safe-webp-queue' ); ?></button>
					<button type="button" class="button" data-ilswq-filter="needs-review"><?php esc_html_e( 'Needs review', 'indexlane-safe-webp-queue' ); ?></button>
				</div>

				<div class="ilswq-table-wrap">
					<table class="widefat striped ilswq-results">
						<thead>
							<tr>
								<td class="manage-column check-column"><input type="checkbox" id="ilswq-check-all" aria-label="<?php esc_attr_e( 'Select all eligible images', 'indexlane-safe-webp-queue' ); ?>" disabled></td>
								<th><?php esc_html_e( 'Attachment', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'File', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Type', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Dimensions', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Original Size', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Est. Memory', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'WebP Size', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Savings', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Editor', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Status', 'indexlane-safe-webp-queue' ); ?></th>
								<th><?php esc_html_e( 'Reason', 'indexlane-safe-webp-queue' ); ?></th>
							</tr>
						</thead>
						<tbody id="ilswq-results-body">
							<tr class="ilswq-empty-row">
								<td colspan="12"><?php esc_html_e( 'Run a scan to build a report.', 'indexlane-safe-webp-queue' ); ?></td>
							</tr>
						</tbody>
					</table>
				</div>
			</section>
		</div>
		<?php
	}

	/**
	 * Save settings via AJAX.
	 *
	 * @return void
	 */
	public function ajax_save_settings() {
		$this->verify_ajax();

		$settings = ILSWQ_Settings::from_request( isset( $_POST['settings'] ) ? $_POST['settings'] : array() );
		$settings = ILSWQ_Settings::save( $settings );

		wp_send_json_success(
			array(
				'settings' => $settings,
			)
		);
	}

	/**
	 * Scan page via AJAX.
	 *
	 * @return void
	 */
	public function ajax_scan() {
		$this->verify_ajax();

		$page     = isset( $_POST['page'] ) ? absint( $_POST['page'] ) : 1;
		$settings = ILSWQ_Settings::from_request( isset( $_POST['settings'] ) ? $_POST['settings'] : array() );

		wp_send_json_success( $this->scanner->scan_page( $page, ILSWQ_Scanner::PER_PAGE, $settings ) );
	}

	/**
	 * Convert selected IDs via AJAX.
	 *
	 * @return void
	 */
	public function ajax_convert() {
		$this->verify_ajax();

		$raw_ids = isset( $_POST['ids'] ) && is_array( $_POST['ids'] ) ? wp_unslash( $_POST['ids'] ) : array();
		$ids     = array();
		foreach ( $raw_ids as $raw_id ) {
			if ( is_scalar( $raw_id ) ) {
				$ids[] = absint( $raw_id );
			}
		}
		$ids = array_filter( $ids );

		$settings = ILSWQ_Settings::from_request( isset( $_POST['settings'] ) ? $_POST['settings'] : array() );
		$ids      = array_slice( $ids, 0, (int) $settings['batch_size'] );

		wp_send_json_success(
			array(
				'rows' => $this->converter->convert_batch( $ids, $settings ),
			)
		);
	}

	/**
	 * Cleanup generated WebP files via AJAX.
	 *
	 * @return void
	 */
	public function ajax_cleanup() {
		$this->verify_ajax();

		$reset = isset( $_POST['reset'] ) && is_scalar( $_POST['reset'] ) ? absint( wp_unslash( $_POST['reset'] ) ) : 0;
		if ( $reset > 0 ) {
			delete_option( ILSWQ_OPTION_CLEANUP_PAGE );
		}

		wp_send_json_success( $this->converter->cleanup_generated( 10 ) );
	}

	/**
	 * Validate one generated WebP attachment map.
	 *
	 * @return void
	 */
	public function ajax_validate_webp() {
		$this->verify_ajax();

		$attachment_id = isset( $_POST['id'] ) && is_scalar( $_POST['id'] ) ? absint( wp_unslash( $_POST['id'] ) ) : 0;
		if ( $attachment_id <= 0 ) {
			wp_send_json_error(
				array(
					'message' => __( 'No attachment selected for WebP validation.', 'indexlane-safe-webp-queue' ),
				),
				400
			);
		}

		$map = ILSWQ_Scanner::get_webp_map( $attachment_id );
		if ( empty( $map ) ) {
			wp_send_json_error(
				array(
					'message' => __( 'No generated WebP files were found for this attachment.', 'indexlane-safe-webp-queue' ),
				),
				404
			);
		}

		foreach ( $map as $entry ) {
			if ( is_array( $entry ) && ! empty( $entry['webp'] ) && file_exists( $entry['webp'] ) && ILSWQ_Scanner::is_valid_webp_file( $entry['webp'] ) ) {
				wp_send_json_success(
					array(
					'message' => __( 'Generated WebP file exists and is valid.', 'indexlane-safe-webp-queue' ),
					)
				);
			}
		}

		wp_send_json_error(
			array(
				'message' => __( 'Generated WebP files are missing or invalid.', 'indexlane-safe-webp-queue' ),
			),
			500
		);
	}

	/**
	 * Optionally convert new uploads after metadata has been generated.
	 *
	 * @param array<string,mixed> $metadata Metadata.
	 * @param int                 $attachment_id Attachment ID.
	 * @return array<string,mixed>
	 */
	public function maybe_convert_upload_metadata( $metadata, $attachment_id ) {
		$settings = ILSWQ_Settings::get();
		if ( empty( $settings['auto_uploads'] ) || empty( $metadata ) || ! is_array( $metadata ) ) {
			return $metadata;
		}

		try {
			$row = $this->converter->convert_attachment_with_metadata( (int) $attachment_id, $settings, $metadata );
			if ( ! empty( $row['status'] ) && in_array( $row['status'], array( 'Failed', 'Needs review' ), true ) ) {
				update_post_meta( (int) $attachment_id, ILSWQ_META_LAST_ERROR, isset( $row['reason'] ) ? (string) $row['reason'] : (string) $row['status'] );
			} else {
				delete_post_meta( (int) $attachment_id, ILSWQ_META_LAST_ERROR );
			}
		} catch ( Throwable $exception ) {
			update_post_meta( (int) $attachment_id, ILSWQ_META_LAST_ERROR, $exception->getMessage() );
		}

		return $metadata;
	}

	/**
	 * Verify AJAX request.
	 *
	 * @return void
	 */
	private function verify_ajax() {
		if ( ! current_user_can( 'manage_options' ) ) {
			wp_send_json_error(
				array(
					'message' => __( 'Permission denied.', 'indexlane-safe-webp-queue' ),
				),
				403
			);
		}

		check_ajax_referer( 'ilswq_admin', 'nonce' );
	}
}
